# Generated by Django 6.0.4 on 2026-04-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'due_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_plants',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_robot_vacuum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
    ]
