# Generated by Django 6.0.4 on 2026-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
