# Generated by Django 6.0.4 on 2026-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.CharField(choices=[('active', 'Актуальные'), ('urgent', 'Срочные'), ('planned', 'В планах')], default='active', max_length=20),
        ),
    ]
