# Generated by Django 6.0.4 on 2026-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recurring_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_list',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
