# Generated by Django 6.0.4 on 2026-05-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
