# Generated by Django 4.2.11 on 2026-05-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringsuggestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
